force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Candidate object holds records of applicants.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Accepted_Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Terms_Conditions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>I have read the above wording and consent to my data being collected and used as described.</description>
    <inlineHelpText>I have read the above wording and consent to my data being collected and used as described.</inlineHelpText>
    <label>Accepted Terms &amp; Conditions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Achievements__c.field-meta.xml
<CustomField>
    <fullName>Achievements__c</fullName>
    <label>Achievements</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Conflict_Of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Conflict_Of_Interest__c</fullName>
    <label>Conflict Of Interest</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Criminal_History__c.field-meta.xml
<CustomField>
    <fullName>Criminal_History__c</fullName>
    <label>Criminal History</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Address__c.field-meta.xml
<CustomField>
    <fullName>Current_Address__c</fullName>
    <label>Current Address</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_City__c.field-meta.xml
<CustomField>
    <fullName>Current_City__c</fullName>
    <label>Current City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_County_State__c.field-meta.xml
<CustomField>
    <fullName>Current_County_State__c</fullName>
    <label>Current County / State</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Employer_Name__c</fullName>
    <label>Current Employer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Job_StartDate__c.field-meta.xml
<CustomField>
    <fullName>Current_Job_StartDate__c</fullName>
    <label>Current Job StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Current_Job_Title__c</fullName>
    <label>Current Job Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Postcode_ZIP__c.field-meta.xml
<CustomField>
    <fullName>Current_Postcode_ZIP__c</fullName>
    <label>Current Postcode / ZIP</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Salary__c.field-meta.xml
<CustomField>
    <fullName>Current_Salary__c</fullName>
    <label>Current Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Employment_History__c.field-meta.xml
<CustomField>
    <fullName>Employment_History__c</fullName>
    <description>Are you currently or have you ever been employed by this organization or its affiliates?</description>
    <inlineHelpText>Are you currently or have you ever been employed by this organization or its affiliates?</inlineHelpText>
    <label>Employment History</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <inlineHelpText>Expected Salary per Annum</inlineHelpText>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
            <value>
                <fullName>Prefer not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Highest_Education_Degree__c.field-meta.xml
<CustomField>
    <fullName>Highest_Education_Degree__c</fullName>
    <label>Highest Education Degree</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Legal_Right_to_Work__c.field-meta.xml
<CustomField>
    <fullName>Legal_Right_to_Work__c</fullName>
    <description>Do you have the Legal Right to Work in the country you are applying to?</description>
    <label>Legal Right to Work</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Permanent_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_City__c</fullName>
    <label>Permanent City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Permanent_County_State__c.field-meta.xml
<CustomField>
    <fullName>Permanent_County_State__c</fullName>
    <label>Permanent County / State</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Permanent_Postcode_ZIP_EIR__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Postcode_ZIP_EIR__c</fullName>
    <label>Permanent Postcode / ZIP / EIR</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Place_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Residence__c</fullName>
    <description>Place of Residence</description>
    <inlineHelpText>Place of Residence</inlineHelpText>
    <label>Place of Residence</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Plain_Text_Cover_Letter__c.field-meta.xml
<CustomField>
    <fullName>Plain_Text_Cover_Letter__c</fullName>
    <description>maximum 700 characters</description>
    <label>Plain Text Cover Letter</label>
    <length>700</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Previously_Worked_Here__c.field-meta.xml
<CustomField>
    <fullName>Previously_Worked_Here__c</fullName>
    <label>Previously Worked Here?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Regulatory_Discipline_History__c.field-meta.xml
<CustomField>
    <fullName>Regulatory_Discipline_History__c</fullName>
    <description>Have you ever been disciplined/cautioned by a regulatory body?</description>
    <label>Regulatory Discipline History</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Relatives_Working__c.field-meta.xml
<CustomField>
    <fullName>Relatives_Working__c</fullName>
    <description>Do you know of any relatives who are working for the area of this Organization you are applying for?</description>
    <label>Relatives Working</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Screening_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Screening_Acceptance__c</fullName>
    <description>If your application is successful , the organization undertakes people screening as part of its recruitment process, these include; criminal records, address verification, academic qualifications, employment dates and employer references — are you happy to continue with your application?</description>
    <label>Screening_Acceptance</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Self_Identified_Disability__c.field-meta.xml
<CustomField>
    <fullName>Self_Identified_Disability__c</fullName>
    <description>Do you consider yourself to have a disability?</description>
    <inlineHelpText>Do you consider yourself to have a disability?</inlineHelpText>
    <label>Self-Identified Disability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Total_Experience__c.field-meta.xml
<CustomField>
    <fullName>Total_Experience__c</fullName>
    <description>Total Experience in months, if the candidate is fresher it should be 0.</description>
    <inlineHelpText>Total Experience in months, if the candidate is fresher it should be 0.</inlineHelpText>
    <label>Total Experience</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Visa_Required__c.field-meta.xml
<CustomField>
    <fullName>Visa_Required__c</fullName>
    <label>Visa_Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No-I am a citizen</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateRestController.cls
@RestResource(urlMapping='/candidateApi/*')
global with sharing class CandidateRestController {
    
    @HttpPost
    global static String createCandidate() {
        String response;

        try {
            RestRequest restRequest = RestContext.request;

            Map<String, Object> params = (Map<String,Object>)JSON.deserializeUntyped(restRequest.requestBody.toString());

            String firstName = (String)params.get('firstName');
            String lastName = (String)params.get('lastName');
            String conflictOfInterest = (String)params.get('conflictOfInterest');
            String employmentHistory = (String)params.get('employmentHistory');
            String criminalHistory = (String)params.get('criminalHistory');
            String legalRightToWork = (String)params.get('legalRightToWork');
            String relativesWorking = (String)params.get('relativesWorking');
            String regulatoryDisciplineHistory = (String)params.get('regulatoryDisciplineHistory');
            String screeningAcceptance = (String)params.get('screeningAcceptance');
            String visaRequired = (String)params.get('visaRequired');
            String emailAddress = (String)params.get('emailAddress');
            String permanentAddress = (String)params.get('permanentAddress');
            String permanentCity = (String)params.get('permanentCity');
            String permanentCountyState = (String)params.get('permanentCountyState');
            String permanentPostcodeZIPEIR = (String)params.get('permanentPostcodeZIPEIR');
            String currentAddress = (String)params.get('currentAddress');
            String currentCity = (String)params.get('currentCity');
            String currentCountyState = (String)params.get('currentCountyState');
            String currentPostcodeZIP = (String)params.get('currentPostcodeZIP');
            String placeOfResidence = (String)params.get('placeOfResidence');
            String mobileNumber = (String)params.get('mobileNumber');
            Decimal totalExperience = (Decimal)params.get('totalExperience');
            String dateOfBirthString = (String)params.get('dateOfBirth');
            Date dateOfBirth = Date.valueOf(dateOfBirthString);
            String previouslyWorkedHere = (String)params.get('previouslyWorkedHere');
            String highestEducationDegree = (String)params.get('highestEducationDegree');
            Boolean acceptedTermsConditions = (Boolean)params.get('acceptedTermsConditions');
            String selfIdentifiedDisability = (String)params.get('selfIdentifiedDisability');
            String plainTextCoverLetter=(String)params.get('plainTextCoverLetter');
            String gender = (String)params.get('gender');
            Decimal currentSalary = (Decimal)params.get('currentSalary');
            Decimal expectedSalary = (Decimal)params.get('expectedSalary');
            String PANNumber = (String)params.get('PANNumber');
            String passportNumber = (String)params.get('passportNumber');
            String currentJobTitle = (String)params.get('currentJobTitle');
            String currentEmployerName = (String)params.get('currentEmployerName');
            String achievements = (String)params.get('achievements');
            String currentJobStartDateString = (String)params.get('currentJobStartDate');
            Date currentJobStartDate = Date.valueOf(currentJobStartDateString);

            Candidate__c newCandidate = new Candidate__c();
            newCandidate.First_Name__c = firstName;
            newCandidate.Last_Name__c=lastName;
            newCandidate.Conflict_Of_Interest__c = conflictOfInterest;
            newCandidate.Employment_History__c = employmentHistory;
            newCandidate.Criminal_History__c = criminalHistory;
            newCandidate.Legal_Right_to_Work__c = legalRightToWork;
            newCandidate.Relatives_Working__c = relativesWorking;
            newCandidate.Regulatory_Discipline_History__c = regulatoryDisciplineHistory;
            newCandidate.Screening_Acceptance__c = screeningAcceptance;
            newCandidate.Visa_Required__c = visaRequired;
            newCandidate.Email_Address__c = emailAddress;
            newCandidate.Permanent_Address__c = permanentAddress;
            newCandidate.Permanent_City__c = permanentCity;
            newCandidate.Permanent_County_State__c = permanentCountyState;
            newCandidate.Permanent_Postcode_ZIP_EIR__c = permanentPostcodeZIPEIR;
            newCandidate.Current_Address__c = currentAddress;
            newCandidate.Current_City__c = currentCity;
            newCandidate.Current_County_State__c = currentCountyState;
            newCandidate.Current_Postcode_ZIP__c = currentPostcodeZIP;
            newCandidate.Place_of_Residence__c = placeOfResidence;
            newCandidate.Mobile_Number__c = mobileNumber;
            newCandidate.Total_Experience__c = totalExperience;
            newCandidate.Date_of_Birth__c = dateOfBirth;
            newCandidate.Previously_Worked_Here__c = previouslyWorkedHere;
            newCandidate.Highest_Education_Degree__c = highestEducationDegree;
            newCandidate.Accepted_Terms_Conditions__c = acceptedTermsConditions;
            newCandidate.Gender__c = gender;
            newCandidate.Self_Identified_Disability__c= selfIdentifiedDisability;
            newCandidate.Plain_Text_Cover_Letter__c= plainTextCoverLetter;
            newCandidate.Current_Salary__c=currentSalary;
            newCandidate.Expected_Salary__c=expectedSalary;
            newCandidate.PAN_Number__c=PANNumber;
            newCandidate.Passport_Number__c=passportNumber;
            newCandidate.Current_Job_Title__c=currentJobTitle;
            newCandidate.Current_Employer_Name__c=currentEmployerName;
            newCandidate.Current_Job_StartDate__c=currentJobStartDate;
            newCandidate.Achievements__c=achievements;
            

            // Insert the new Candidate record
            insert newCandidate;

            response = '{"candidateId": "' + newCandidate.Id + '"}';
        } catch(Exception e) {
            response = '{"errorMessage": "Error creating Candidate: ' + e.getMessage() + '"}';
        }

        return response;
    }
}